### ISSUE TITLE
Component does not emit anything on blur event

### ISSUE THREAD

**Issue by kalcifield** [EducationLink/vue-tel-input#10]
In case one wants to show error message after blur.

**Comment by kalcifield** [comment]
My suggestion:
adding @blur.native to input field
           <b-form-input  @blur.native="onBlur" />

adding a method:
             onBlur() { this.$emit('onBlur', this.response) }

**Comment by iamstevendao** [comment]
Closed in [v2.0.0](https://www.npmjs.com/package/vue-tel-input), please check [events](https://github.com/EducationLink/vue-tel-input#events)
