### ISSUE TITLE
how to remove the space between numbers before submit?

### ISSUE THREAD

**Issue by nekooee** [EducationLink/vue-tel-input#102]
hi,
I need to save a number without space between numbers. how I can remove the space between numbers before submit and after submit completely reformat numbers?

**Comment by Timibadass** [comment]
Hi @nekooee , you can do so like this before sending the phone number
`var phone = this.phone;`
`phone = phone.replace(/\s+/g, '');`

**Comment by nekooee** [comment]
> Hi @nekooee , you can do so like this before sending the phone number
> `var phone = this.phone;`
> `phone = phone.replace(/\s+/g, '');`

Hi @Timibadass, a phone number is a bind to form and if I remove space manually, in the phone field change too. I need to remove space between numbers before send and reformat it after sending the form. Currently, I force remove space between the number on the server-side.

**Comment by Timibadass** [comment]
@nekooee , the above format wouldhelp you remove the space..if you use it just before attaching the `phone` to the body of the request.An example would be 
`sendPhoneToServer() {
 var phone = this.phone;
phone = phone.replace(/\s+/g, '');
axios.post(url,{
phone: phone
})
}`

**Comment by nekooee** [comment]
@Timibadass I send all form fields with an array that bind to form. for example:
```javascript
  data() {
            return {
                formContent: {},
                errors: {},
            }
        },
 methods: {
            onSubmit() {
                axios.post(`admin/roles`, this.formContent)
```

That's why I can not replace my own variable.

**Comment by iamstevendao** [comment]
Now we use [awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber) behind the scene. @nekooee you can listen to the `input` event and use anything available from the returned object. Here is a sample:

```json
{
  "canBeInternationallyDialled": true,
  "number": {
      "input": "0707123456",
      "international": "+46 70 712 34 56",
      "national": "070-712 34 56",
      "e164": "+46707123456",
      "rfc3966": "tel:+46-70-712-34-56",
      "significant": "707123456"
  },
  "regionCode": "SE",
  "valid": true,
  "possible": true,
  "type": "mobile",
  "possibility": "is-possible"
}
```

**Comment by renzocastillo** [comment]
happens the same to mwe @nekooee . I am also using a form variable to get all inputs and send them to server. How did you solve it ?

TY

**Comment by nekooee** [comment]
> happens the same to mwe @nekooee . I am also using a form variable to get all inputs and send them to server. How did you solve it ?
> 
> TY

This is a long time ago and I do not remember how I used it. Maybe I upgraded to a new version.
