### ISSUE TITLE
"open" event not emiting

### ISSUE THREAD

**Issue by boazasd** [EducationLink/vue-tel-input#104]

**Comment by iamstevendao** [comment]
@boazasd Sorry, there was a bit of delay here. I will release the new version with the `open` and `close` events tonight.

**Comment by boazasd** [comment]
just saw its a super fresh update :)
thanks

**Comment by iamstevendao** [comment]
Closed on [v2.4.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.0)
