### ISSUE TITLE
Cannot import to my NUXT project

### ISSUE THREAD

**Issue by yothin-workout** [EducationLink/vue-tel-input#105]
Here is my set up :

1. npm i --save vue-tel-input

2. create vue-tel-input.js to /plugins
`import Vue from 'vue';`
`import VueTelInput from 'vue-tel-input' ;`
`import 'vue-tel-input/dist/vue-tel-input.css';`
`Vue.use(VueTelInput)`

3. add ~nuxt.config.js
`plugins: [ "~/plugins/vue-tel-input" ],`

 4.in my component
`<vue-tel-input />`

Vue warning :
`"export 'default' (imported as 'VueTelInput') was not found in 'vue-tel-input'`

` Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

Is my set up is correct ?

**Comment by iamstevendao** [comment]
I think you need to use:
```
import VueTelInput from "vue-tel-input";
import "vue-tel-input/dist/vue-tel-input.css";

Vue.component('vue-tel-input', VueTelInput);
```

You can see my created sample here in Nuxt: https://codesandbox.io/s/codesandbox-nuxt-977bd

**Comment by yothin-workout** [comment]
Hey!! 

I changed my vue-tel-input.js code and still get this error 
`"export 'default' (imported as 'VueTelInput') was not found in 'vue-tel-input' `

so I see your created sample in Nuxt -> [https://codesandbox.io/s/codesandbox-nuxt-977bd](url)
and Here is the result. Please check it.

![image](https://user-images.githubusercontent.com/38827684/60636272-fca04180-9e3f-11e9-8478-3a1c0582be23.png)

**Comment by iamstevendao** [comment]
@yothin-workout That's super strange!! Here is my screenshot:
![Screen Shot 2019-07-04 at 19 16 42](https://user-images.githubusercontent.com/15044203/60655010-60eaf180-9e90-11e9-99aa-b934df90e893.jpg)

**Comment by PrimeDominus** [comment]
This example no longer works. You can see https://github.com/EducationLink/vue-tel-input/issues/url no longer renders, and I get Nuxt render errors on my local machine. @iamstevendao Can you try your example on local to see if it works for you, and if not, please advise? 😄

**Comment by iamstevendao** [comment]
@PrimeDominus I think you need to wrap the component in the `<no-ssr>` tag to tell Nuxt not to render it in the server-side. I created a new sandbox: https://codesandbox.io/s/vue-tel-input-nuxt-demo-1l93b

**Comment by PrimeDominus** [comment]
@iamstevendao thanks a bunch 😄 This works! For those reading this, I tested this locally and got a console warning that `<no-ssr>` tags will be deprecated in Vue 3.0+ and it recommends using `<client-only>` tags instead. I've tried this and it works 🎉

**Comment by DominicGBauer** [comment]
For plugins you can add `mode: 'client'` like this:

{ src: '~plugins/vue-tel-input', mode: 'client' }

If you only want the plugin to be loaded client side.
