### ISSUE TITLE
Use something else than simple-get?

### ISSUE THREAD

**Issue by voluntadpear** [EducationLink/vue-tel-input#107]
Just as a suggestion since I had an issue with `vue-tel-input` in a Meteor project due to `simple-get`. Uglify was complaining abut an parse error due to `simple-get` (which was really difficult to find). I ended up forking `vue-tel-input` and replacing `simple-get` with `axios`. I could send a PR with my changes if you'd like to use Axios but I understand that it is perhaps a too big dependency. Did you consider perhaps just using the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)?

Either way, awesome component! Thank you for this

**Comment by iamstevendao** [comment]
@voluntadpear I will give it a test on a Meteor project. 
Also, thanks for the suggestion, I haven't used `Fetch API` ever but I will take a look :)

**Comment by iamstevendao** [comment]
@voluntadpear, we are using `Fetch API` from [v2.5.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.5.0). Let me know if it works in your meteor project now :)
