### ISSUE TITLE
CSS Conflict with vuetify

### ISSUE THREAD

**Issue by jeck5895** [EducationLink/vue-tel-input#11]
Button / Link styles are being changed when importing vue-tel-input.css
![image](https://user-images.githubusercontent.com/22309354/40712291-e586b6f0-642f-11e8-8b65-0b89e99f2689.png)

**Comment by mikob** [comment]
likely because of the bootstrap dependency, does this work for you: https://github.com/EducationLink/vue-tel-input/pull/13
