### ISSUE TITLE
Different Bundle Size For NPM & YARN Installs.

### ISSUE THREAD

**Issue by pxwee5** [EducationLink/vue-tel-input#115]
So I installed this package differently, one with `npm install` and `yarn`. Output in bundle analyzer are different. 

NPM Install
![image](https://user-images.githubusercontent.com/14123790/61604034-150fb900-ac94-11e9-8bb5-a80cc9f3f610.png)

Yarn Install
![image](https://user-images.githubusercontent.com/14123790/61604022-06290680-ac94-11e9-9eae-b274353d7e8d.png)

Thoughts?

**Comment by iamstevendao** [comment]
@pxwee5 Im not sure what happens here. But as we released [v3.0.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.0.0) with vue cli build tool, it might fix this problem?

**Comment by iamstevendao** [comment]
Close due to inactivity.
