### ISSUE TITLE
how to remove outline from control, list and country-selector?

### ISSUE THREAD

**Issue by DenniLa2** [EducationLink/vue-tel-input#117]
subject

**Comment by iamstevendao** [comment]
@DenniLa2 maybe something like this would help? Everything is wrapped in class `vue-tel-input` so you can customize everything inside without breaking other parts from your app.

![Screen Shot 2019-07-23 at 10 51 18](https://user-images.githubusercontent.com/15044203/61674631-febb3900-ad37-11e9-828d-9c8ce9f6105d.jpg)

**Comment by DenniLa2** [comment]
@iamstevendao I can not understand, how can I remove outline from div ((
![image](https://user-images.githubusercontent.com/9018493/61685563-d1fe2600-ad25-11e9-9049-1f681ed1e5c3.png)

**Comment by iamstevendao** [comment]
@DenniLa2 I don't think it comes from `vue-tel-input`. There might be other styles messing it up?

**Comment by DenniLa2** [comment]
@iamstevendao on screen - applied styles with high priority.

**Comment by iamstevendao** [comment]
@DenniLa2 I see. It turns out to be the `.vue-tel-input:focus-within`, you can override the `border` and `box-shadow` of it:

![Screen Shot 2019-07-24 at 10 49 23](https://user-images.githubusercontent.com/15044203/61756735-dd724f80-ae00-11e9-85cf-893d308506bf.jpg)
