### ISSUE TITLE
How to get the country code 

### ISSUE THREAD

**Issue by hsouiri97** [EducationLink/vue-tel-input#121]
after adding v-model to the component it seems that it only give you the phone number without formatting it with the country code. is there anyway to achieve that?

**Comment by iamstevendao** [comment]
It's achievable in [v.3.1.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.0) by setting prop `mode: 'international'`, in this case, the phone number will always be converted to +123 123 123...
