### ISSUE TITLE
Phone example in placeholder

### ISSUE THREAD

**Issue by powerlimit** [EducationLink/vue-tel-input#122]
Hi everyone. is it possible to set phone example in placeholder? for example, if my country is germany, in placeholder i want see +49 30 123456, if russia, +7 301 123-45-67 etc.

**Comment by iamstevendao** [comment]
@powerlimit. Done! It's available by setting prop `dynamicPlaceholder: true` from [v3.1.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.0)
