### ISSUE TITLE
Typescript typings wrong in v3

### ISSUE THREAD

**Issue by MihkelPuusepp** [EducationLink/vue-tel-input#128]
![image](https://user-images.githubusercontent.com/34569528/63037245-5e37df00-bec7-11e9-94c1-8c41ad67e0e3.png)

**Comment by rentorm** [comment]
@MihkelPuusepp I've provided fix for this in official 'DefinitelyTyped' repository so once it's in you can update your '@types/vue-tel-input' module dependency

**Comment by iamstevendao** [comment]
@rentorm Thanks for your help!!

**Comment by rentorm** [comment]
PR with fix has been merged in 'DefinitelyTyped' repository. @MihkelPuusepp can you please check if this is working now?
