### ISSUE TITLE
wrapperClass

### ISSUE THREAD

**Issue by denjaland** [EducationLink/vue-tel-input#130]
Hi,

I'm adding some wrapperClasses from TailwindCSS, such as `outline-none`, `border-none`.
However, since vue-tel-input class is also applied, they are still being applied from that class.

Any idea what the most elegant way of overriding these css rules might be?

**Comment by iamstevendao** [comment]
Maybe something like (these are all border and outline of `vue-tel-input`):
```
.vue-tel-input {
  border: unset !important;
}
.vue-tel-input:focus-within {
  box-shadow: unset !important;
}
```

**Comment by SebastianMieszczanczyk** [comment]
It is not working - did you check it? You cant use `!important` on `focus-within` selector and also on element selector, beacause it will choose the second selector and `focus-within` styles wont be applied. You have custom options: wrapperClasses and InputClasses but even if you set it, they will be overwritten by default. I think there must be same improvement here. E.g. change the selectors for those with lower specificity.
