### ISSUE TITLE
Bug with Russian number 

### ISSUE THREAD

**Issue by LePashtet** [EducationLink/vue-tel-input#132]
When number is 8 (964) 534-35-44 and i delete last symbol it becomes 8 (896) 453-43-54 One more 8 added, and it's really strange

**Comment by iamstevendao** [comment]
@LePashtet I think it's fixed in [v3.1.7](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.7), I close it for now but feel free to re-open if it's still happening.
