### ISSUE TITLE
Autofocus wrong prop type

### ISSUE THREAD

**Issue by palfaro91** [EducationLink/vue-tel-input#136]
Just started using this library and I am seeing this error in the console. It's not present in 3.1.0
```
[Vue warn]: Invalid prop: type check failed for prop "autofocus". Expected String, got Boolean with value false.
```
Should the prop type be Boolean rather than String?

**Comment by iamstevendao** [comment]
Thanks @palfaro91, it's fixed in [v3.2.1](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.2.1).
