### ISSUE TITLE
Feature request: Changing selected country from outside the component

### ISSUE THREAD

**Issue by TheGreenAirplane** [EducationLink/vue-tel-input#137]
Hello, would it be possible to add the option to change the selected country from the component's parent?
Currently I can disable fetching the country, and provide a default country, but that only sets the country when the component loads.
I have a dropdown list on my page where the user can select a country, and based on his selection other elements dynamically change their state. I need the selected country in the vue-tel-input component to change too.

**Comment by iamstevendao** [comment]
From `v3.3.0`, you can do something like this:
```html
// template
<vue-tel-input ref="telInput"></vue-tel-input>
```

```js
// script
this.$refs.telInput.choose('AU')
```
