### ISSUE TITLE
Unkown Custom element

### ISSUE THREAD

**Issue by stotes** [EducationLink/vue-tel-input#14]
[Vue warn]: Unknown custom element: <b-row> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VueTelInput>

Am I missing a dependency?

**Comment by stotes** [comment]
I ended up using the @mikob fork that removed the dependency

**Comment by iamstevendao** [comment]
[v2.0.0](https://www.npmjs.com/package/vue-tel-input) published along with @mikob's pull request.
