### ISSUE TITLE
No CSS version dist file possible?

### ISSUE THREAD

**Issue by seanhakbb** [EducationLink/vue-tel-input#144]
I upgraded to the latest v4 from 2, and think its great with all the new features and awesome-phonenumber.
However I would like to be able to load the sprite and styles myself, would it be possible to get a no-css version of the dist?

Thanks for the great work!

**Comment by Tofandel** [comment]
+1, having the css globally included in js is super annoying, the postcss rules of webpack are not applied since they are in a javascript file

**Comment by cjlaborde** [comment]
This needs to be done, is a real letdown that the component doesn't match my site design style.
Would prefer if it was more subtle than the grey blue focus.

**Comment by divdax** [comment]
Any news on this?

**Comment by iamstevendao** [comment]
From `v5`, css will be extracted to a file: `vue-tel-input/dist/vue-tel-input.css`.
