### ISSUE TITLE
Unable to get entire phone number with v-model

### ISSUE THREAD

**Issue by raedzawawi** [EducationLink/vue-tel-input#146]
![image](https://user-images.githubusercontent.com/7217472/67900019-1e2ce380-fb29-11e9-99ff-bac96c9f3184.png)

I am using multiple vue-tel-input components as child components on my page. I am using v-for to create these components according to the number of users and tying each user's number to the number attribute in an object called contact (v-model="data.contact.number"). However, I am only receiving the information in the "Number" field and not the entire number with the country code. Is there a way that I can actually get "+1 (604) 999-999" instead of just "(604) 999-999"?

`
<vue-tel-input
                wrapperClasses="row"
                inputClasses="form-field__input"
                placeholder="Number"
                v-model="data.contact.number"
                :inputId="'pax' + (index + 1)"
                sortedOn="dialCode"
                defaultCountry="CA"
                v-bind="bindProps">
</vue-tel-input>
`

Apologies for creating an issue. Didn't know where else to ask this question.

T

**Comment by iamstevendao** [comment]
@raedzawawi, Don't worry! issues is the place for questions too 😄. Have you tried prop `mode: 'internaltional'`?
https://codesandbox.io/s/bold-butterfly-0yyyk45q7w

Feel free to re-open it again if you have any other questions.

**Comment by raedzawawi** [comment]
Thank you for the quick response Steven. Unfortunately, I tried the international mode, however, then I also see the +1 added in the number field. It also removes the brackets. My company wants that specific format and functionality as shown in the screenshot. I was thinking more in the sense that maybe we could get the whole phoneObject back using v-model, so I could merge the areaCode and the number myself. That way I could also see whether the number is valid or not for some form validation on submit.

**Comment by iamstevendao** [comment]
@raedzawawi, I see, in that case, you can use the `@input` event instead of using `v-model` to listen to the changes and get the `PhoneNumber` object.
