### ISSUE TITLE
Feature request: Current element as third argument

### ISSUE THREAD

**Issue by jayakornk** [EducationLink/vue-tel-input#154]
### Description:
It would be really nice to have reference to current element as the third argument directly on input event. This would benefit if the component has been used in several places and has to pass through some mapping function in order to store current value in different variable according to current focused element.

### Usage:

```js
getMobilePhone(phoneText, phoneObject, element) {
  const classes = element.classList;
  classes.forEach((class) => {
    switch (class) {
      case 'one':
        // do something
        break;
      case 'two':
        // do something
        break;
      default:
        // do something
        break;
    }
  });
}
```

Thanks for a very great component btw.

**Comment by iamstevendao** [comment]
Available in [v5.0.4](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.4)
