### ISSUE TITLE
Error in beforeCreate hook: "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by Ximenakdi** [EducationLink/vue-tel-input#156]
![image](https://user-images.githubusercontent.com/38775140/71533445-4bdea080-28be-11ea-8d31-76e42ba671a6.png)

when i saw what really was the problem, it shows me that is in vue-tel-input.umd.js

**Comment by iamstevendao** [comment]
Is it related to #105?

**Comment by Ximenakdi** [comment]
No, it was working very well, I added some props and everything was perfect, then I reloaded the page and the error showed up

**Comment by iamstevendao** [comment]
It looks like the error is from the server side, can you try this? https://nuxtjs.org/guide/plugins/#client-side-only

**Comment by Ximenakdi** [comment]
i tried, and it kinda work.
now when i reload the page this shows up, again:
![image](https://user-images.githubusercontent.com/38775140/71551348-2aa7ae00-29ab-11ea-8430-6f2e40ac09cf.png)

when i reload it again, it shows this:
![image](https://user-images.githubusercontent.com/38775140/71551355-414e0500-29ab-11ea-81cc-c74c6a711630.png)

when i reload for the third time, the normal page appears, but the error keeps showing in the console

**Comment by iamstevendao** [comment]
Can you try this https://github.com/EducationLink/vue-tel-input/issues/105#issuecomment-574213389?  Is there any chance you can reproduce it some where, like here https://codesandbox.io/s/vue-tel-input-nuxt-demo-1l93b?

**Comment by draigar** [comment]
Making it load only on client side NuxtJs worked for me
