### ISSUE TITLE
List of countries

### ISSUE THREAD

**Issue by AlexeyDnepr** [EducationLink/vue-tel-input#16]
Suggestion. Add to package custom property as onlyCountries, which contains limited list of countries abbrevs

**Comment by iamstevendao** [comment]
It's a good idea. We will have it in the next version.

**Comment by AlexeyDnepr** [comment]
Thnks!

**Comment by yauri-io** [comment]
@iamstevendao 
I sent a pull request for this feature because I also need the feature 😅
#46

**Comment by hriad** [comment]
Hello,
I'd like to also add a feature request which is related to this one: Add the ability to blacklist a list of countries.

**Comment by iamstevendao** [comment]
@yauri-io I left comments on your PR, I'm hoping you would fix it so that I can merge :). If you are tight on time I will fix it myself.

**Comment by iamstevendao** [comment]
@yauri-io, @hriad 
I added 2 new props `onlyCountries` and `ignoredCountries`, which are what you guys want, please update to v2.0.12
