### ISSUE TITLE
Show short country code in the input with flags and phone code

### ISSUE THREAD

**Issue by arieltoledo** [EducationLink/vue-tel-input#161]
Hi, great component ! 
I wonder if there's a way to achive something like this ... 
Couldn't find the way with the docs. 
Thanks !

<img src="https://i.imgur.com/QVm2bGC.png" />
<img src="https://i.imgur.com/RWDcCw4.png" />

**Comment by 03balogun** [comment]
You can achieve this by setting the `enabledCountryCode` the global options to `true`. Sample code below

```
...
import VueTelInput from 'vue-tel-input';

Vue.use(VueTelInput, {
  enabledCountryCode: true,
});

...
```

or directly using props

```
  <vue-tel-input v-model="phone" enabledCountryCode="true"></vue-tel-input>

```

**Comment by arieltoledo** [comment]
@03balogun  Hi, thanks for your answer, the enabledCountryCode prop adds from phone code. I was wondering if I could show of country code like [US, BR, PY, PA] enstead the complete country name

**Comment by alcheco** [comment]
@arieltoledo I noticed that you can replace the name of the countries adding the **allCountries** prop in the configuration. 

You can see an example of this on the vue-telinput.esm.js file from the node_modules between the 38 and 77 line.

In this code you can notice that the **allCountries** prop needs an array of countries with this elements for every country: name, iso2, dialCode, priority and areaCodes.

Everything can be overwritten in your code without touching the node module, and you can put the iso2 on the name.

**Comment by iamstevendao** [comment]
Thanks @alcheco :+1: well explained.
