### ISSUE TITLE
document is not defined with SSR

### ISSUE THREAD

**Issue by cavinpabua** [EducationLink/vue-tel-input#163]
I'm making my project with vue-tel-input but my problem upon implementing SSR is that it shows document is not defined.

**Comment by ElSiham** [comment]
I don't know if there is a way to make it work in ssr.
My solution was to only call it client side (I'm using nuxt) :

- Add `mode: 'client'` in nuxt.config.js

`{ src: '~plugins/vue-tel-input.js', mode: 'client' }`

- Then put the `<no-ssr>` tags around the vue-tel-input tag in your component or `<client-only>` if you're using nuxt v2.9.0:

`<no-ssr>
      <vue-tel-input />
 </no-ssr>`

Hope it helps

**Comment by cavinpabua** [comment]
@ElSiham Thank you! Works like a charm!
