### ISSUE TITLE
Few questions and one suggestion

### ISSUE THREAD

**Issue by nezaboravi** [EducationLink/vue-tel-input#165]
Hello
I am using vue-tel-input as a child component.
My Main component is PhoneRegistrationModel.
``` 
 <div class="flex flex-col py-2 mt-6 w-96 justify-between">
                <span class="flex border-b-1" :class="phoneError ? 'border-a4a-btn-red' : ''">
                    <vue-tel-input
                        v-model="tel"
                        wrapperClasses="h-12 border-b-1 border-red-500 w-96"
                        autocomplete="mobile"
                        inputClasses="w-full"/>
                </span>
                <div class="flex items-end" :class="phoneError ? 'justify-between' : 'justify-end'">
                    <span class="text-xs italic text-red-500" v-if="phoneError">{{phoneError}}</span>
                    <span class="text-xs italic text-a4a-light-grey self-end" :class="phoneError ? 'text-a4a-btn-red' : ''">required</span>
                </div>
            </div>
```
Using latest Chrome on Mac.
Now let me explain problems:
1) autocomplete="mobile" - whatevever i set as autocomplete, always shows my email.
2) autocomplete="off" - shows my email
3) I can enter anything i want in input field, does not shows me if field is valid  as on example.
4) On v-model i see the number as i type it, but there is not like in example where i can see country code as well: +66 956789... 
Questions:
1) How can i display if phone is valid
2) How can i get full number with country code?

TO mention, i see all of these things in Vue dev tools, inside vue-tel-input component. The problem is i dont see them in parent (PhoneRegisterModal)

Less important: How i can stop input field to be populated with email instead to be empty or prepoluted with a phone number. To mention, i have tried: autocomplete="off", both on form and field, atucomplete="tel" autocomplete="mobile" 

SUGGESTION:
Not bale to see i its implemented, but would be great when form validation fails, and user start typing to remove existing error message.

Thanks
V

**Comment by iamstevendao** [comment]
@nezaboravi Sorry for the delay.
- If you want to see what is the value of country, validation or full number, you can use the [`@input`](https://www.npmjs.com/package/awesome-phonenumber) event, the second argument will be the PhoneNumber object from [awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber).

- Also, to prevent users from typing letters, you can set the prop `valid-characters-only: true`.
