### ISSUE TITLE
Show dial code overrides current phone number

### ISSUE THREAD

**Issue by adrianmann** [EducationLink/vue-tel-input#168]
Am I right in saying that `showDialCode: true` in `inputOptions` overrides the current phone number?

I am playing with the CodePen here: https://codesandbox.io/s/vue-tel-input-playground-wznqo . I have changed the value of `showDialCode` to true and the number (`phone: 0123456789`) is not shown on the screen as seen here: https://wznqo.csb.app/ .

Is there a way to show the dial code if there is no number supplied only or is this a bug or a feature? Also, is there a way to show the dial code in addition to a value, in this case `phone`, in the code sandbox linked?

Edit: I see the scenario above is happening because mode is international. Can a selected dial code be appended to a non international phone number any way by clicking on it?
 The constant closing and reopening was not to draw attention. I genuinely thought I had gotten somewhere and then realised I hadn't.

**Comment by LouisCharles70** [comment]
I am having the same problem here.. Thanks !

**Comment by adrianmann** [comment]
@LouisCharles70 If it helps, the [input event](https://github.com/EducationLink/vue-tel-input#events) has a isValid object which contains the international version of the number, `isValid.number.international`. You can use this to populate your input field. `isValid.number.international` is the value of the phone number you had previously and any selected phone extension.

**Comment by iamstevendao** [comment]
From `v5` you can turn off the auto format option by `autoFormat: false`.
