### ISSUE TITLE
How to apply custom validation in vue-tel-input

### ISSUE THREAD

**Issue by adrianmann** [EducationLink/vue-tel-input#169]
As the title says, what is the process to applying a customValidate regex in vue-tel-input? I have a standard setup like in this code sandbox.

My props:
```
smsProps: {
        disabledFetchingCountry: true,
        placeholder: "Please enter your SMS number",
        maxLen: 50,
        selectedCountryCode: true,
        preferredCountries: ["US", "GB"],
        inputOptions: { showDialCode: false },
        customValidate: /^\+\d+$/
      }
```

The code hangs and kills my browser without any error messages when I open and close a modal and then reopen the same modal. Is my formatting correct or is there another approach I should take? Is my regex ok? Does it mater if the field is disabled? Can customValidate conflict with the default formatting of vue-tel-input that is applied?

**Comment by adrianmann** [comment]
I needed to allow for a space character in my regex.

**Comment by iamstevendao** [comment]
@adrianmann, Please pass a variable with the type RegExp, like this: `customValidate: new RegExp('^\+\d+$')`. Also please check if your custom validation allows numbers, the custom validation will override the default validation of `vue-tel-input`.

**Comment by adrianmann** [comment]
@iamstevendao Thanks Steven, I will try that but it may be some time before I get to verify it but maybe I should close this issue anyways. I would have simply specified the customValidate as shown in my opening comment so that is probably it.

**Comment by sataqi** [comment]
@iamstevendao tried with `customValidate: new RegExp('^\+\d+$')` but same result browser hangs up. any help on this please?

**Comment by AlexeyShaykov** [comment]
same problem

put 

<vue-tel-input

:customValidate="customValidate"


data {
customValidate: new RegExp(/^\+\d+$/),
}

vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'join' of null
    at VueComponent.cleanInvalidCharacters (vue-tel-input.umd.min.js?e75b:1)
    at VueComponent.mounted (vue-tel-input.umd.min.js?e75b:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4219)
    at Object.insert (vue.runtime.esm.js?2b0e:3139)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6346)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6565)
    at VueComponent.Vue._update (vue.runtime.esm.js?2b0e:3948)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
