### ISSUE TITLE
defaultCountry props is not reactive

### ISSUE THREAD

**Issue by Richard-Richie** [EducationLink/vue-tel-input#173]
Example : 
`<vue-tel-input :defaultCountry='countryCode' v-model="value"></vue-tel-input>`
data(){
    return{
      countryCode : 'US'
    }
}

**Comment by darthsoup** [comment]
i have the same problem. Without that its not possible using this on Edit Pages, because its always using the Components default country

**Comment by Richard-Richie** [comment]
> **Edit**
> It works for me if i use remove the `national` from `mode`

Could you explain me in brief?

**Comment by don-nez** [comment]
@darthsoup @Richard-Richie 

if you're planing to use defaultCountry prop to re-populate your form for editing in a CRUD operations well...the library uses a method called "choose" to set the active country , it takes a country is "iso" name as its only parameter , so now u need a way to access child component is data there's 3 ways i can think of , in my project i use vue is "ref" feature : 

```
<template>
    <vue-tel-input ref="phoneNumber" v-model="value"></vue-tel-input>
  </template>

<!-- in one of your methods -->
  this.$refs.phoneNumber.choose("USA"); // set country to usa
```

**Comment by Richard-Richie** [comment]
'toLowerCase' of undefined"

**Comment by safal07** [comment]
My solution was to force re-render the component on country code change. To do that, I added a key same as country code, on code change, the key should be updated and vue force re-renders your component.

`<vue-tel-input :defaultCountry='countryCode' v-model="value" :key='countryCode'></vue-tel-input>`

**Comment by rayets123** [comment]
> 'toLowerCase' of undefined"

this.$refs.phoneNumber.choose({iso2:"USA"});  
it works

**Comment by iamstevendao** [comment]
From `v5` you can do `this.$refs.phoneNumber.choose('AU')`
