### ISSUE TITLE
Component's class css rules override my classes css rules

### ISSUE THREAD

**Issue by scheMeZa** [EducationLink/vue-tel-input#183]
I can't apply a class to the wrapper to remove the border.

The only way I can remove the border is by adding `!important` to my class' CSS rules. This is annoying because I'm using Tailwindcss, and I don't want to manually add !important to every single rule I have because it would break styling elsewhere.

**Comment by Shade465** [comment]
I have the same problem

**Comment by waltergammarota** [comment]
Not a permanent solution, but I unset the css and wrap it to solve it quick:

`<div class="form-input border w-full rounded p-1">
<vue-tel-input
class="w-full"
placeholder="011 50502727"
v-model="phone"
></vue-tel-input>
</div>`

`.vue-tel-input {
  border: unset !important;
}
.vue-tel-input:focus-within {
  box-shadow: unset !important;
}`

**Comment by BSYoann** [comment]
It's a general problem with vue and style in component. To override css you have to do it with a more specific css selector than just a class.

```html
<vue-tel-input class="phone"></vue-tel-input>
```

Style override:
```css
.vue-tel-input.phone {
  border: none;
}
```

It also works with id since it's a more specific selector than classes:
```html
<vue-tel-input id="phone"></vue-tel-input>
```

Style override:
```css
#phone {
  border: none;
}
```

**Comment by iamstevendao** [comment]
From [v5.1.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.1.0), you can import separate CSS files, so I recommend only importing `sprite.css` and copy the style of `component.css` to your component, change it as you want.
