### ISSUE TITLE
Options onlyCountries seems to change listing order 

### ISSUE THREAD

**Issue by Yummy123123** [EducationLink/vue-tel-input#187]
Hello,

Using option "onlyCountries" seems to change the order of the country displayed.
I wanted to select only some countries but keep the default alphabetic order but instead it keep the order specified inside onlyCountries options. 

I think this is not the behaviour that should be used.

What do you think about it ?

Thanks

See : https://github.com/Yummy123123/vue-tel-input/commit/e6bca9db4918568e5fd9d56bbee99c39172a327d#diff-8f0933bb907db7c1cbc31e8b649644a0

**Comment by iamstevendao** [comment]
Fixed in [v4.4.1](https://github.com/EducationLink/vue-tel-input/releases/tag/v4.4.1).
