### ISSUE TITLE
component lazyload

### ISSUE THREAD

**Issue by alqa-dash** [EducationLink/vue-tel-input#189]
Hello, 

Could you help me to manage lazy load of vue-tel-input as component? Its assets are pretty huge and I tried to load it lazily but with no success. I tried the following approach:

`components: {
    VueTelInput: () => import('vue-tel-input')
}`

But in this case I got warning and input is not rendered:

> [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueTelInput>
       <AppVisit> at src/views/Visit.vue
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>

How can I load VueTelInput as component lazily?

Thanks,
Dmitry

**Comment by iamstevendao** [comment]
@alqa-dash This works but I'm not sure if the lazy-load works, you can create a wrapper else where too.
```
components: {
  VueTelInput: async () => {
     const { VueTelInput } = await import('vue-tel-input');
     return VueTelInput;
  }
}
```

**Comment by alqa-dash** [comment]
@iamstevendao Thanks! Yes it works but is does not help with lazy-load.
