### ISSUE TITLE
Missing area code for Canada

### ISSUE THREAD

**Issue by jsshapiro** [EducationLink/vue-tel-input#202]
In assets/all-countries.js, in the record for Canada (CA), area code 367 is missing. This looks like a typo. 387 is present, but area code 387 has not (yet) been allocated by NANPA.

Recommendation:

1. Add area code 387
2. Take a few moments to look at the current NANPA area codes for Canada and add the _other_ area codes that are currently missing.

**Comment by iamstevendao** [comment]
@jsshapiro we don't use `all-countries.js` to format the phone number, only to return the country object to client. [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) takes care of it.
