### ISSUE TITLE
impossible to disable formatting for a phone number

### ISSUE THREAD

**Issue by VallyPepyako** [EducationLink/vue-tel-input#204]
I see here https://educationlink.github.io/vue-tel-input/  disabledFormatting prop, but it do nothing and this prop missed in github documentation

**Comment by ElpixZero** [comment]
Yes, i have the same problem.

I expected some prop for controlling it. For example, i enter phone number "+79285552211", tel-input is formatting it to "+7926 555-22-11" and returning this value ("+7926 555-22-11") to me, but i want got get value without formatting ("+79285552211").

I really don't know how to do it..

**Comment by iamstevendao** [comment]
From [`v.5.0.0`](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.0), we have option to turn off formatting `autoFormat: false`
