### ISSUE TITLE
Model shows value without country code

### ISSUE THREAD

**Issue by asolopovas** [EducationLink/vue-tel-input#209]
Hi,
When I enter value model does not contain the country code.
![image](https://user-images.githubusercontent.com/6893216/89734598-076ed200-da55-11ea-8c77-9eabecbfb19c.png)

![image](https://user-images.githubusercontent.com/6893216/89734613-19507500-da55-11ea-9e21-26c2b94dfde3.png)

**Comment by batuhanoztrk** [comment]
It can be corrected by adding the mode="international" probe.  In this case, the phone number will always be converted to +123 123 123...

`<vue-tel-input
              mode="international"
              :enabledCountryCode="true"
              id="phone"
              inputClasses="form-control"
              v-model="data.phone"
              :validCharactersOnly="true"
            >`

**Comment by iamstevendao** [comment]
Thanks @batuhanoztrk!
