### ISSUE TITLE
Return country object instead of country name

### ISSUE THREAD

**Issue by janbalaz** [EducationLink/vue-tel-input#21]
Hi,
firstly, thanks for this plugin, it looks like the best vue specific plugin for this purpose, especially after Bootstrap dependency was removed :)

Anyway would be good to get country object in the onInput callback instead of just country name. In my use case I need to also send country alpha2 code to the backend.

I found possible workaround by using ref on vue-tel-input element and then accessing activeCountry.

**Comment by iamstevendao** [comment]
@janbalaz sure we can easily add it so that you don't need to work around. I will do it very soon!

**Comment by iamstevendao** [comment]
@janbalaz Included in v2.0.2, sorry for the delay
