### ISSUE TITLE
reduce bundle size

### ISSUE THREAD

**Issue by khaledosman** [EducationLink/vue-tel-input#213]
According to bundlephobia the library seems to be 400.6kB minified and 146.1kB minified + gzipped https://bundlephobia.com/result?p=vue-tel-input@4.4.0 potentially slowing down the initial render

This seems to be quite a lot for just an input field library , is there a reason for that or a way to reduce the bundle size?

**Comment by olivier-js** [comment]
Same problem here.

**Comment by iamstevendao** [comment]
`v5` should fix this:
<img width="732" alt="Screen Shot 2021-01-21 at 17 34 39" src="https://user-images.githubusercontent.com/15044203/105300545-f387e880-5c0e-11eb-934c-0b14c0141fff.png">
