### ISSUE TITLE
i18n : Change countries name

### ISSUE THREAD

**Issue by bat79a** [EducationLink/vue-tel-input#214]
Hi and thx a lot for this lib who is awesome.

But, Is there a way to change the names of the countries, so that they are displayed for example in French ?

I saw that you use intl-tel-input that can change the list, so I think that it's possible to do the same work nop ?
(https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/modify-country-data.html)

Thx a lot for your answer.

**Comment by iamstevendao** [comment]
@bat79a you can replace all countries with prop `allCountries`: https://educationlink.github.io/vue-tel-input/documentation/props.html
