### ISSUE TITLE
How to disable the automatic formatting of phone numbers

### ISSUE THREAD

**Issue by bertms** [EducationLink/vue-tel-input#215]
When I input the number, it will automatically modify the format: (361) 254-6589. I don't want to do this. I checked the configuration and did not find the relevant configuration. "Mode" does not have this option.

**Comment by antoci-alin** [comment]
Looking forward for this too. It would be a great improvement to have an option to disable formatting.

**Comment by biholaindrasinh** [comment]
`import PhoneNumber from 'awesome-phonenumber';`
`var pn = new PhoneNumber(this.form.phone, 'SE')`
` this.phone = pn.getNumber('significant')`

**Comment by jasper-moment** [comment]
I was hoping to get automatic formatting. How come I don't have it?

**Comment by iamstevendao** [comment]
It's available in [`v.5.0.0`](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.0) with `autoFormat: false`.
