### ISSUE TITLE
not able to set country code dynamically

### ISSUE THREAD

**Issue by pendem14** [EducationLink/vue-tel-input#222]
i am able to select the country code and able to save it in DB. however i am not able to set the country code dynamically. can you please suggest me how we can set country dynamically. not the defaultcountry.

**Comment by StevenMalaihollo** [comment]
Same problem.

**Comment by aa84899** [comment]
can you try it

private phoneCountryCd: string = 'us';
private contactNum: string = ''; 
<vue-tel-input
                                    :defaultCountry="phoneCountryCd"
                                    v-model="contactNum"
                                    :key="phoneCountryCd"
                                    @onInput="contactNumEvent"
                                    @blur="primaryPhoneValidation"
                                ></vue-tel-input>

and set the contactNum and phoneCountryCd in the created vue lifecycle.

**Comment by aa84899** [comment]
> i am able to select the country code and able to save it in DB. however i am not able to set the country code dynamically. can you please suggest me how we can set country dynamically. not the defaultcountry.

i tired with the following code and it works fine for me

private phoneCountryCd: string = 'us';
private contactNum: string = '';
<vue-tel-input
:defaultCountry="phoneCountryCd"
v-model="contactNum"
:key="phoneCountryCd"
@onInput="contactNumEvent"
@blur="primaryPhoneValidation"
>

and set the contactNum and phoneCountryCd in the created vue lifecycle.

**Comment by DevyDalton** [comment]
It's also an option to use this: `this.$refs.telInput.choose('NL');`

This way you can select every county dynamically.

**Comment by rayets123** [comment]
> It's also an option to use this: `this.$refs.telInput.choose('NL');`

There you need to transfer the object in the method choose() like {iso2: 'NL'}
this.$refs.telInput.choose({iso2:'NL'});

**Comment by iamstevendao** [comment]
From [`v.5.0.0`](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.0) you can do `this.$refs.telInput.choose('NL')`.
