### ISSUE TITLE
cant find country code 

### ISSUE THREAD

**Issue by easy-techno** [EducationLink/vue-tel-input#227]
I can't find the country code on the form submit with telephone input and also after selecting the country the cursor moves to the front of the +1  instead of the end. this lids the user to enter a false format this shud be fexed

**Comment by oaraujocesar** [comment]
You need to add the prop `mode="international"` to the input. This way when you blur the input you'll get the number with the country code. Hope it helps!

**Comment by iamstevendao** [comment]
@oaraujocesar Thank you!
