### ISSUE TITLE
Not able to disable the telephone number formatting

### ISSUE THREAD

**Issue by das-devi** [EducationLink/vue-tel-input#230]
![image](https://user-images.githubusercontent.com/36114359/103230929-99bc3780-495c-11eb-8f0d-8dc129d957a5.png)

@Team,
I have a 10 digit mobile number with the country code ex: +17036877205 coming from my backend service, but when I try to bind it to vue-tel-input box its getting formatting getting displayed as (703) 687-7205, I do not wan to show '(' and  ')' symboles and the spaces between the numbers, I want it to display as 7036877205 with the country flag based on the country code.

I tried by setting the prop value disabledFormatting="true", but still I can able to see the formatting can you please help here?

code snippet 

<vue-tel-input
                                    :defaultCountry="phoneCountryCd"
                                    v-model="contactNum"
                                    :key="phoneCountryCd"
                                    data-ut="numberInput"
                                    @keydown="resetMessage"
                                    @mousedown="resetMessage"
                                    @onInput="contactNumEvent"
                                    disabledFormatting="true"
                                ></vue-tel-input>

**Comment by simllll** [comment]
Guess you are looking for autoFormat?
<vue-tel-input
....
:autoFormat="false"
>

**Comment by iamstevendao** [comment]
`autoFormat` is available from [`v.5.0.0`](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.0)
