### ISSUE TITLE
ignoredCountries is still allowing phone number to be validated if typed manually

### ISSUE THREAD

**Issue by redvivi** [EducationLink/vue-tel-input#231]
Environment: vue-tel-input v4.4.0

**Actual behaviour**

1. Set a country in ignoredCountries prop (example: PK)
2. Type in the phone number in that country in international format: +92 349 6866608
3. Even if the country is not selectable in the drop-down list, this phone number goes past the validation

**Expected behaviour**

Step 3: The phone number of an ignored country should not be validated.

**Comment by Chernavskikh** [comment]
Hello, maybe my PR will be helpful

**Comment by iamstevendao** [comment]
Thanks to @Chernavskikh, available in [v5.0.4](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.4)
