### ISSUE TITLE
this.resetPlaceholder is not a function after updating to version 5.0.0

### ISSUE THREAD

**Issue by kramalexx** [EducationLink/vue-tel-input#233]
I get the source code from CDN and just in few minutes major version was updated and I started to get this error. 
Looks like this method was just commented by a mistake or something.

![image](https://user-images.githubusercontent.com/42442717/104693569-f40a1600-571a-11eb-98fb-d37f28b89a1e.png)

Also the input itself started looking like below 

![image](https://user-images.githubusercontent.com/42442717/104693837-5f53e800-571b-11eb-95f5-cdd2c1858572.png)

Temporarily downgraded to the version 4.4.2.

Thanks!

**Comment by iamstevendao** [comment]
@kramalexx Thank you! I commented out the `dynamicPlaceholder` prop in the last minute and this happened. `v5.0.1` is out with the fix.
