### ISSUE TITLE
Browser version break after update to version 5

### ISSUE THREAD

**Issue by anujchhabria1** [EducationLink/vue-tel-input#234]
We are using the browser version and we've imported the below CDN URL's:
<script src="https://unpkg.com/vue-tel-input"></script>
<link rel="stylesheet" href="https://unpkg.com/vue-tel-input/dist/vue-tel-input.css">

Along with this, i am installing it to Vue, like: Vue.use(VueTelInput)

However, we are receiving the following error: ReferenceError: Can't find variable: VueTelInput.

**Comment by iamstevendao** [comment]
@anujchhabria1, from `v5` you can do `Vue.use(window['vue-tel-input']`.
