### ISSUE TITLE
support for new 10 digit numbers for Côte d’Ivoire

### ISSUE THREAD

**Issue by anjolabassey** [EducationLink/vue-tel-input#238]
The package does not support the new 10 digit phone number for Côte d’Ivoire as annouced by The "Autorité de Régulation des Télécommunications/TIC de Côte d’Ivoire" [here](https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast#:~:text=The%20%22Autorit%C3%A9%20de%20R%C3%A9gulation%20des,2021%20in%20C%C3%B4te%20d'Ivoire.) effective 31 January 2021

**Comment by iamstevendao** [comment]
@anjolabassey I don't think it's supported by `google/libphonenumber` yet: https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html
