### ISSUE TITLE
How to detect country from number?

### ISSUE THREAD

**Issue by rminossi** [EducationLink/vue-tel-input#239]
Hello,

How to automatically detect the country according to the existing phone number? I intend to use the package also on the registration edit form, where the phone number will come from the database. Is there a way to do this?

Tks,

**Comment by iamstevendao** [comment]
@rminossi as long as the number includes the dial code, you can get the country from the `@input` event.

**Comment by rminossi** [comment]
@iamstevendao could you give me an example? it wasn't clear to me.

**Comment by iamstevendao** [comment]
@rminossi it's the same way we are using in the demo page: https://educationlink.github.io/vue-tel-input/
If you click on "Show options" you will see the phone object with country code.
The code of demo page: https://github.com/EducationLink/vue-tel-input/blob/master/docs/.vuepress/theme/components/Home.vue

**Comment by rminossi** [comment]
Tks, @iamstevendao, now i understand... <3
