### ISSUE TITLE
Please provide an example for usage of inputOptions.styleClasses

### ISSUE THREAD

**Issue by orhanveli** [EducationLink/vue-tel-input#240]
Hi there

I need an example for usage of `inputOptions.styleClasses`. Here is my usage but I don't see any effect.

```js
<vue-tel-input
  v-model="currentRecipientData.phone"
  :valid-characters-only="true"
  :input-options="{
    styleClasses: {
      'form-control': true,
      'has-error': $v.currentRecipientData.phone.$error,
      'current-recipient': true
    }
  }"
  :preferred-countries="['gb', 'br', 'es', 'fr', 'de', 'it', 'pt', 'nl']"
  @input="onPhoneNumberInput"
></vue-tel-input>
```

any idea?

**Comment by iamstevendao** [comment]
@orhanveli `inputOptions.styleClasses` adds classes to the `input` inside `vue-tel-input`, if you want to add classes to `vue-tel-input` itself, use `styleClasses`.

**Comment by orhanveli** [comment]
exactly, I'm trying to add class to the input.

**Comment by iamstevendao** [comment]
@orhanveli what version are you using? this prop is for v5+

**Comment by orhanveli** [comment]
ah OK my version looks `4.4.2`. thanks
