### ISSUE TITLE
Change placeholder "Enter your phone number"?

### ISSUE THREAD

**Issue by VIMHaos** [EducationLink/vue-tel-input#25]
Hi, thanks for your plugin,) 
Would be fine to add placeholder and label props for choise, like as https://vuetifyjs.com/ru/components/text-fields

**Comment by ATselikovSnp** [comment]
you can just write  <vue-tel-input v-model="phone" placeholder="12 123 45 67"></vue-tel-input>

**Comment by iamstevendao** [comment]
Thanks, @ATselikovSnp

**Comment by VIMHaos** [comment]
Thanks, @ATselikovSnp 
You have right, in new plugin version we can change placeholder, I uses old version 1.3.9,
but in new version 2.0 not uses keyboard filter, how it's do that in old version

**Comment by iamstevendao** [comment]
@VIMHaos what is the "keyboard filter" you are talking about? would you like to give me more details?

**Comment by VIMHaos** [comment]
Hi, @iamstevendao
Try input text to field not number, in old version this blocked

**Comment by fbtwitter** [comment]
I still had this error problem, using props placeholder is not working for me..

anyway how to use inputOptions.placeholder in my component ?

Thank you

**Comment by iamstevendao** [comment]
@fbtwitter Can you reproduce it anywhere?

**Comment by fbtwitter** [comment]
I still had this problem, where the placholder props won't running reactive as well.. until i tried to refresh the page.
those newer version are great.. hopefully the documentation for trying the new version updated sooner..

**Comment by iamstevendao** [comment]
@fbtwitter it should be working on [v5.0.3](https://github.com/EducationLink/vue-tel-input/releases/tag/v5.0.3)

**Comment by iamstevendao** [comment]
@constagorgan the prop is `inputOptions.placeholder`, not `placeholder`.

**Comment by constagorgan** [comment]
Thanks for your quick reply @iamstevendao, and please excuse my lack of attention. I didn't notice that the prop name changed in the recent versions.

It works perfectly fine with `inputOptions` 😃

In case someone else needs more details, I'll leave this here:
```
<template>
  ...
  <vue-tel-input v-model="..."
                 @onInput="..."
                 :inputOptions="options"">
  </vue-tel-input>
</template>
<script>
  ...
  data() {
    return {
      options: { placeholder: "Some placeholder" }
    }
  }
  ...
</script>
```

Result:
![image](https://user-images.githubusercontent.com/9217700/105368745-81ada000-5c0a-11eb-80c3-2b796215dbc5.png)

![image](https://user-images.githubusercontent.com/9217700/105368557-5925a600-5c0a-11eb-837e-d4f498d051cd.png)

**Comment by iamstevendao** [comment]
@constagorgan it's cool ✌️

**Comment by arieltoledo** [comment]
@constagorgan  Hi, I try to followed your example but Im getting inputoptions=[object Object ] instead. Thanks.

```
<vue-tel-input
   :only-countries="codigos_paises"
   :valid-characters-only="true" 
   :inputOptions="tel_options"
   enabled-country-code
   @input="onInput"  />
```
```
var app = new Vue ({
        el: '#page',
        data: {
                tel_options: {
                        'placeholder': "Ingrese su número de telefóno"
                },
.....


```
![Sin nombre](https://user-images.githubusercontent.com/3604845/108228948-15955d80-711e-11eb-8aef-48ad00046cbf.png)

**Comment by constagorgan** [comment]
Hi @arieltoledo, sorry for getting back to you just now. In case you're still struggling with this problem:

Could you please try rewriting your JS like:

```
var app = new Vue ({
  el: '#page',
  data() {
    return {
      tel_options: {
        'placeholder': "Ingrese su número de telefóno"
      }
    }
  }
...
```

**Comment by arieltoledo** [comment]
@constagorgan Thanks, changing Vue versión and rewriting the code to worked.

**Comment by darrylferdinands** [comment]
Is there no way to add a red asterisk at the end of the placeholder?
