### ISSUE TITLE
There should be prop named "disabled"

### ISSUE THREAD

**Issue by ATselikovSnp** [EducationLink/vue-tel-input#26]
Now if I want to disable input for phone number and dropdown for countries I must do it manually through the DOM methods, it's not good to do so. So I think there should be :disabled prop, so I can just pass one parameter and the component will add :disabled attribute to input and hide dropdown.

**Comment by iamstevendao** [comment]
@ATselikovSnp Thanks for the suggestion, included in [v2.0.2](https://www.npmjs.com/package/vue-tel-input)

**Comment by rublev** [comment]
How about disabling all countries except preferred?
