### ISSUE TITLE
Input to field not number

### ISSUE THREAD

**Issue by VIMHaos** [EducationLink/vue-tel-input#27]
In new version 2.0 not uses keyboard filter (entered chars is not blocked)
![vue-tel-input](https://user-images.githubusercontent.com/24316505/43201233-285e1432-9018-11e8-9be3-93649667801e.jpg)

**Comment by mstrlaw** [comment]
Should still be able to handle the _+_ symbol in case user tries to set it manually.

**Comment by ATselikovSnp** [comment]
And if correct number has already been entered vue-tel-input won't produce error, which is produced while there no correct number.
Without error:
![image](https://user-images.githubusercontent.com/40032061/45230131-a1113000-b2d0-11e8-9e98-7cc213bd737b.png)
With error:
![image](https://user-images.githubusercontent.com/40032061/45230170-bb4b0e00-b2d0-11e8-9ddb-e8932d1b1416.png)

**Comment by shershen08** [comment]
Any updates on this one?
this behaviour with letters allowed in the end of the input is quite strange UX 
![Screen Shot 2019-05-24 at 15 42 29](https://user-images.githubusercontent.com/1363772/58332003-a0a6ce00-7e3a-11e9-966e-35a29b39d78b.png)

**Comment by mariusgen** [comment]
I am using this, in my component, to ignore the unwanted characters:
`watch: {
      dataPhoneModel(newValue, oldValue) {
        const re = /^([+]?){1}[\s./0-9]*$/
        if (!re.test(newValue)) {
          this.$nextTick(() => {
            this.dataPhoneModel = oldValue
          })
        }
      },
    }`

**Comment by iamstevendao** [comment]
Thanks for the patience guys. From [v2.4.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.0) we have `validCharactersOnly` to prevent letters and invalid characters. It's not perfect yet but the best I can do :(.
I leave this issue open in case someone wants to improve it.

**Comment by Alexandernoa** [comment]
I have a problem with the characters that should be available to users. Could you add more one prop for prevent all characters except numbers ? Or how can I change default validation to custom ?

With `validCharactersOnly` users can do this:
![image](https://user-images.githubusercontent.com/10417130/70332688-2fb58980-1853-11ea-8ac0-83b085c291ec.png)

**Comment by iamstevendao** [comment]
@Alexandernoa from `v5`, `validCharactersOnly` won't allow `*` anymore
