### ISSUE TITLE
v-model works only one-way, when it's supposed to work two-way.

### ISSUE THREAD

**Issue by ATselikovSnp** [EducationLink/vue-tel-input#28]
My vue-tel-input component looks like this: ` <vue-tel-input v-model="phone"></vue-tel-input>`.
It changes phone in data of its parent component, but when i change phone in parent component vue-tel-input isn't changing its phone data value. Here's the picture of vue-tel-input state:
![image](https://user-images.githubusercontent.com/40032061/43216644-308f1914-9048-11e8-8d31-60d7b3b20699.png)
As you can see value is passed through v-model, but it's not set in the data of the component. It shoud be set, because v-model means two-way binding and not one-way, like it works now.
To reproduce it you can do it like that:
`<vue-tel-input v-model="phone"></vue-tel-input>
<input v-model="phone">`
When you are typing something into  vue-tel-input it will change what is displayed in simple input, but when you are typing into simple input nothing will change in vue-tel-input.

**Comment by filipwronski** [comment]
I have the same problem, my dirty fix for this issue is to clear field by js.. Don't do this in Home ;) -  ex.document.querySelectorAll("#tel2 > input")[0].value = '';

**Comment by devinle** [comment]
If I'm following this correctly (I also have a parent wrapper), it appears as though the vue-tel-input only looks for its value on the created() hook. I'm loading the data async from an API, so I'm curious–if this component also had an updated() hook that was identical to the created() hook, it might present the data properly.

**Comment by devinle** [comment]
I found a solution for my use case. In my wrapper, I have an updated() method. I provide a ref attribute to the vue-tel-input component. When updated fires, I assign a value to the ref data phone prop.

`
<vue-tel-input
    ref="tel"
    :value="value"
    :placeholder=placeholder            
    @onInput="onInput"
>
...
updated() {
    const child = this.$refs.tel;
    child.phone = this.value;
},
`

**Comment by devinle** [comment]
After a few tests, I believe it has to do with async data piped through from the parent wrapper component. Within the vue-tel-input component, there is only a created() hook that sets the internal phone data value. Here's how I was able to resolve in my parent wrapper.

**First, give the vue-tel-input a ref attribute**

```
<vue-tel-input
    ref="tel"
    :value="value"
    :placeholder=placeholder            
    @onInput="onInput"
></vue-tel-input>
```

**Then, add an updated method to the parent wrapper. This assumes you are setting a data property called value.**

```
updated() {
    const child = this.$refs.tel;
    if(!child.phone) {
        child.phone = this.value;
    }
},
```
