### ISSUE TITLE
It's not possible to set 'separateDialCode' option

### ISSUE THREAD

**Issue by matteomelotti** [EducationLink/vue-tel-input#29]
It's not possible to set 'separateDialCode' option or other options of International Telephone Input plugin.

**Comment by raphaelarias** [comment]
Currently, it's not possible, would you be able to do a pull request?

**Comment by iamstevendao** [comment]
Available via prop `enabledCountryCode: true`, you can set `mode: 'national'` if you want to format without the dial code in the input (+xx).
