### ISSUE TITLE
How to set country programmatically?

### ISSUE THREAD

**Issue by Kinzi** [EducationLink/vue-tel-input#33]
I use this in a checkout form with IP detection which works out fine most of the time.
However I also have a country field and I would like to change the tel country prefix according to the country field value.

Is it possible to override the country somehow?

**Comment by iamstevendao** [comment]
@Kinzi Thanks for the suggestion, we will have this feature in the next update.

**Comment by Kinzi** [comment]
@iamstevendao Cool. Ideally it would just be an optional prop like so:

`<vue-tel-input v-model="phone" :country="myCountry"></vue-tel-input>`

Where you could override the country with the ISO code(so "AU" for "Australia"). See here: https://github.com/umpirsky/country-list/blob/master/data/en/country.json

**Comment by iamstevendao** [comment]
@Kinzi. v2.0.6.
Now we can pass `defaultCountry` (country iso code) to `vue-tel-input`, it will be selected by default and bypass the country fetched from the user's location.

**Comment by Cookizza** [comment]
I have noticed that setting `defaultCountry` actually stops you from selecting a new country :( ideally it would clear the prefix from the input when changed and then act as normal

**Comment by hardikmandaviya** [comment]
Hey I am also facing this issue and that one is still not work properly as say in above questions.

**Comment by tkoop** [comment]
I'm also having this issue.  It would be nice to set the country whenever I want to.

**Comment by dcruz1990** [comment]
Guys, you have to pass a country ISO to the `choose()` function. That does the work.

**Comment by AndTras** [comment]
usa and canada have the same code, but when selecting by iso it always selects usa. :/
