### ISSUE TITLE
v2.0.5 should not be a minor

### ISSUE THREAD

**Issue by lipsumar** [EducationLink/vue-tel-input#36]
Our build broke today because of version 2.0.5

One of the changes in this version is *the removal of a full directory*. This is clearly not minor change as it's not backward compatible.

I'm not proposing to change the version now, but in the future it would be nice to consider backward compatibility and thus stick to [semver](https://semver.org/).

Thanks in advance

**Comment by iamstevendao** [comment]
@lipsumar, I'm sorry about that. I got into some troubles authenticating my npm account before, and then I ignore `dist` folder and for some reasons, it got messed up.
Is anything good now?

**Comment by lipsumar** [comment]
Well I’m now stuck on v2.0.0

How about a v2.0.6 that adds back the “dist” directory?

**Comment by iamstevendao** [comment]
@lipsumar done. v2.0.6 is out.
