### ISSUE TITLE
Autocomplete dialCode when the number is still not valid

### ISSUE THREAD

**Issue by f1729** [EducationLink/vue-tel-input#41]
In this case i try with Perú.

Perú needs **9 digits** without counting the dial code(+51), to be valid, however it marks as valid in addition to completing the dial code having only 8 digits.

<img width="560" alt="screen shot 2018-09-19 at 17 49 37" src="https://user-images.githubusercontent.com/23299193/45786095-95106100-bc34-11e8-8aa1-8771152c1a71.png">

**Comment by iamstevendao** [comment]
Thanks @f1729, fixed in v2.0.8
