### ISSUE TITLE
Country list selector appear behind certain components (z-index)

### ISSUE THREAD

**Issue by afloury** [EducationLink/vue-tel-input#47]
The country list selector appears behind specific components.
I'm using Vuetify on my project and components like button are in front of the country list selector.
![image](https://user-images.githubusercontent.com/18677074/48973879-17a90880-f04a-11e8-9e11-074dee345849.png)

I fork the repository and correct the problem by adding `z-index: 1;` on `<ul>` of the dropdown.

**Comment by afloury** [comment]
Hi @iamstevendao 
Can you review my PR please 😄

**Comment by iamstevendao** [comment]
From what I understand here, you can set the `z-index: 1` for `vue-tel-input` inside your component where you use it.
Something like
```
<style>
.vue-tel-input .dropdown ul {
  z-index: 1;
}
</style>
```

**Comment by afloury** [comment]
Thanks, but it's not working

**Comment by iamstevendao** [comment]
@afloury, your request is now available in v2.0.12 :)

**Comment by JordanRClark** [comment]
If anyone is reading this, and you want to get a z-index over 1 - be sure to be using non-scoped scss.  This should work:

```<style lang="scss">
  div.vue-tel-input div.dropdown ul {
    z-index: 2 !important;
  }
</style>```

**Comment by Nehasoni988** [comment]
> If anyone is reading this, and you want to get a z-index over 1 - be sure to be using non-scoped scss. This should work:
> 
> ```
> <style lang="scss">
>   div.vue-tel-input div.dropdown ul {
>     z-index: 2 !important;
>   }
> </style>
> ```

Hey,
Is this working for you? I am not able to fix this. I am on Vuetify 3 and this country selector is still behind Vuetify components.
