### ISSUE TITLE
Vue.js 2: Country search should not be case sensitive.

### ISSUE THREAD

**Issue by Darshan562** [EducationLink/vue-tel-input#485]
Issue
Country search doesn't work for input containing capital letters (INDIA, inDIa) in Vue.js 2

Steps to reproduce

Enable dropdown options with showSearchBox: true
Type INDIA and check dropdown options
Type inDIa and check dropdown options

codesandbox link :-
https://codesandbox.io/p/sandbox/jovial-nova-ft698j?file=%2Fsrc%2FApp.vue%3A19%2C31

![image](https://github.com/user-attachments/assets/bf081345-310a-4747-a33f-9188d710d5bb)

**Comment by cuongle-hdwebsoft** [comment]
Hi @Darshan562, I've been fixed this issue. Now you can use it in `v5.16.0`. Let me know if you have any question. Thanks

**Comment by Darshan562** [comment]
Hi @cuongle-hdwebsoft, thanks for this solution.
