### ISSUE TITLE
Cant resolve fs & net.

### ISSUE THREAD

**Issue by ChadTaljaardt** [EducationLink/vue-tel-input#5]
ERROR in ./~/vue-tel-input/dist/vue-tel-input.common.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\ctaljaardt\Documents\GitHub\Caselight\user_interface\node_modules\vue-tel-input\dist'
 @ ./~/vue-tel-input/dist/vue-tel-input.common.js 1:164316-164329
 @ ./~/vue-tel-input/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

ERROR in ./~/vue-tel-input/dist/vue-tel-input.common.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\ctaljaardt\Documents\GitHub\Caselight\user_interface\node_modules\vue-tel-input\dist'
 @ ./~/vue-tel-input/dist/vue-tel-input.common.js 1:164486-164500
 @ ./~/vue-tel-input/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.j

**Comment by Spatlani** [comment]
+1

**Comment by hehoo** [comment]
+1

**Comment by Spatlani** [comment]
After searching around for a while, this fixed my issue https://github.com/webpack-contrib/css-loader/issues/447

**Comment by joesweeny** [comment]
+1

**Comment by iamstevendao** [comment]
guys sorry for the delay, we will take a look and get back to you soon

**Comment by fvanhove** [comment]
+1

**Comment by ewarth** [comment]
+1

**Comment by HasmedFara** [comment]
+1

**Comment by MarouaneZizah** [comment]
+1

**Comment by alisarac** [comment]
Adding config below to webpack works for me if you are using webpack
`
node: {
    fs: 'empty',
    net: 'empty'
}
`

**Comment by iamstevendao** [comment]
Thank you guys for all the delay, the new version is up [v1.3.5](https://www.npmjs.com/package/vue-tel-input).
The usage is changed a bit as well, please check the [README](https://github.com/EducationLink/vue-tel-input/blob/master/README.md).

I will close this issue for now, but if you guys still find it doesn't work, feel fee to open it again
