### ISSUE TITLE
country change event

### ISSUE THREAD

**Issue by muralivenkatesh** [EducationLink/vue-tel-input#50]
Hi,

when entered the mobile number. After changing the country need to remove old values and country also need to change

**Comment by muralisugu** [comment]
Answer:

https://github.com/EducationLink/vue-tel-input/blob/master/src/vue-tel-input.vue

In this above link go to line no 338

You can add below code it will work fine.
choose(country) {
      this.activeCountry = country; 
      this.phone='';
      this.$emit('onInput', this.response);
    },

**Comment by Revel109** [comment]
@raphaelarias @iamstevendao 
This issue has been solved. Update the latest changes from repo.

Use this prop: `:selectedCountryCode="true"`

Now, After changing the country it's removing old values and country codes also changing.

**Comment by iamstevendao** [comment]
Thank to @Revel109, this issue has been fixed in `v2.0.20` with prop: `inputOptions: { showDialCode: true }`.
