### ISSUE TITLE
how to i disable auto format value

### ISSUE THREAD

**Issue by theara72** [EducationLink/vue-tel-input#52]
i don't need auto formatt to visible to user input , can i disable this auto formatted ? THank

**Comment by sirsquall** [comment]
+1

**Comment by sirsquall** [comment]
Or at least on the "onInput" send the raw value?

**Comment by sirsquall** [comment]
Maybe the way I did it is not the right one, what do you think if your method returns an object like that: 
`{
'full_phone': "+xx xx xxxx xxx"
'phone': "xx xxx xxx"
'country': "+xx"
'country_code': "AU"
}`

What do you think? It's easier to keep the backward compatibility?

Cheers,

**Comment by iamstevendao** [comment]
@sirsquall, Thanks for your support. I'm taking a look into your PR and I'm also concerned about the backward compatibility as well.
Adding the raw input from the user to the `onInput` event might be a good solution.

**Comment by sirsquall** [comment]
Thank you very much Steven

**Comment by iamstevendao** [comment]
`v2.0.16` is up with supporting for `disabledFormatting` prop. it's supposed to work as you wish and you still be able to achieve the 'formatted number' by `formattedNumber` returned from `onInput` event.

**Comment by sirsquall** [comment]
Everything is working well, thank you very much, for your time and reactivity!

**Comment by adrianmann** [comment]
How can I disable formatting in 4.3.0?

**Comment by jasper-moment** [comment]
Interestingly I was hoping to get formatting when you all are discussing how to disable. How come I don't see formatting visible to users with default config?

**Comment by jasper-moment** [comment]
I see why. I set max-len to be 10 (for US). Wondering how I can have both..

**Comment by jasper-moment** [comment]
Setting it to 13 works 🥴

**Comment by sirsquall** [comment]
Hello Jasper,

I was interested in storing the number in a database, this is why I was looking to disable the formatting. But I kept the formatting for the frontend 👍 

Thanks
