### ISSUE TITLE
How to check response without editing phonenumber?

### ISSUE THREAD

**Issue by pxamike** [EducationLink/vue-tel-input#53]
Hi!

If I use vue-tel-input and define a v-model that already contains a phone-number, I see that vue-tel-input internally checks and knows if it's valid or not, but how can I know this from the parent component?

I am looking for a way for vue-tel-input to emit the response back to its parent without directly editing the field (which would trigger onInput).

A typical usercase is submitting a form without doing changes to the (prefilled) telephone-number field and making sure vue-tel-input find the number valid.

Do you have an idea?

**Comment by iamstevendao** [comment]
If you just want to use the emit event `onInput` then you don't need the `v-model`
Something like 
```
<template>
...
   <vue-tel-input  @onInput="onInput"></vue-tel-input>
...
<template>
<script>
export default {
  data() {
    return {
      phone: '',
    };
  },
  methods: {
     onInput({ number, isValid, country }) {
       this.phone = number; // Your validation and variable here
     },
  },
}
</script>
```

**Comment by pxamike** [comment]
Thanks for the quick reply.

Ok, but how would that make vue-tel-input validate a prefilled number? From your example the vue-tel-input component would be a blank field, wouldn't it?

Altering your example, how could vue-tel-input tell me if this number is valid without the user interacting with it? Sorry if I'm missing something obvious.

```
<template>
...
   <vue-tel-input v-model="phone" @onInput="onInput"></vue-tel-input>
...
<template>
<script>
export default {
  data() {
    return {
      phone: '12345', // an invalid phonenumber
    };
  },
  methods: {
     onInput({ number, isValid, country }) {
       this.phone = number; // Your validation and variable here
     },
  },
}
</script>
```

**Comment by pxamike** [comment]
@iamstevendao

**Comment by pxamike** [comment]
@iamstevendao Thank you, it is. :) :+1:

**Comment by flowser** [comment]
how do i use the onValidate?  
<template>
...
   <vue-tel-input  @onInput="onInput"></vue-tel-input>
...
<template>
<script>
export default {
  data() {
    return {
      phone: '',
    };
  },
  methods: {
     onInput({ number, isValid, country }) {
       this.phone = number; // Your validation and variable here
     },
  },
}
</script>

**Comment by pxamike** [comment]
@flowser if you want to use your onInput-method on onValidate-events, simply add @onValidate="onInput" to your vue-tel-input tag, I think.
