### ISSUE TITLE
:preferredCountries don't work

### ISSUE THREAD

**Issue by alexeydg** [EducationLink/vue-tel-input#57]
```
 <vue-tel-input 
v-model="phone"
 :required="true"
:preferredCountries="['us','uk','fr','de','fi','au','mx','br','sw','es','is']">
</vue-tel-input>
```
result:
![2019-02-06_14-07-48](https://user-images.githubusercontent.com/2332107/52337432-ace85600-2a18-11e9-92b3-71f15c6865f0.png)

**Comment by iamstevendao** [comment]
That's weird, I copy your code to test in the demo file and it works.
Are you missing something? also, the code for UK is 'gb', you can take a look at the `assets/all-countries.js` to see all the code we are using.

![screen shot 2019-02-28 at 23 05 27](https://user-images.githubusercontent.com/15044203/53565380-72a04d80-3bad-11e9-91f6-7229ec593eef.jpg)

**Comment by Bibendus83** [comment]
@alexeydg Try with :preferred-countries instead of :preferredCountries
