### ISSUE TITLE
Chrome autofill broken

### ISSUE THREAD

**Issue by Agilix** [EducationLink/vue-tel-input#58]
Hi,

We're using this plugin in our VueJs app and noticed something was off.

Whenever you enter a number manually everything works as expected.
But when you use the autofill in chrome the hidden fields stay empty.
This means our users will see the fields being filled in but nothing is saved.

To combat this we wanted to use  `autocomplete='off'` but this is not passed onto the hidden input fields.

Any ideas of what we might be able to do?

And thank you for all the work put into this plugin, much appreciated!

**Comment by YamenSharaf** [comment]
I have the same issue

**Comment by Agilix** [comment]
@YamenSharaf We went with a `autocomplete="off"` on a form element surrounding the input fields. That did the job for not allowing autocomplete.

But we're considering removing vue-tel-input in the future as a lot of our customers complain about not having autocomplete.

**Comment by YamenSharaf** [comment]
@Agilix I thought this is something that should be trivial, so I made a PR here to address this issue. Hope it gets merged soon

https://github.com/EducationLink/vue-tel-input/pull/63

**Comment by iamstevendao** [comment]
Thanks guys, I merged PR from @YamenSharaf, please update to `v2.0.14`.
