### ISSUE TITLE
Impossible to listen to events in Vue 2

### ISSUE THREAD

**Issue by Haggai-Mac** [EducationLink/vue-tel-input#61]
The events 'onInput', 'onValidate' and 'onBlur' are camelCased and thus can't work in Vue 2 since listening to the kebab-cased version will have no effect and the v-on event listeners will be automatically transformed to lowercase (due to HTML’s case-insensitivity).

**Comment by iamstevendao** [comment]
@Haggai-Mac are you sure? we are doing fine in the demo, please see `demo/App.vue`.

**Comment by Haggai-Mac** [comment]
[Vue tip]: Event "oninput" is emitted in component <VueTelInput> but the handler is registered for "onInput". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "on-input" instead of "onInput".

**Comment by Haggai-Mac** [comment]
@iamstevendao [Vue tip]: Event "oninput" is emitted in component <VueTelInput> but the handler is registered for "onInput". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "on-input" instead of "onInput".

**Comment by iamstevendao** [comment]
@Haggai-Mac I see. I don't want to bring some changes that might break the usage of others who are relying on this element for now.
We will have an update to fix this issue in a near future.
Would you mind telling me why can't you use the camelCase in this case?

**Comment by pretty** [comment]
This is a  big issue, can't register event handlers on the component in our app either, see here: https://vuejs.org/v2/guide/components-custom-events.html

Need a fix for this somehow

**Comment by iamstevendao** [comment]
@pretty @Haggai-Mac Done in b5187c2306236b1286ce29d9dd61f0310ee2aa4c (`v2.2.0`) guys. now the events are `input`, `blur`, `validate`,... check out the README for more details :)
