### ISSUE TITLE
Persistent country code

### ISSUE THREAD

**Issue by SamanthaChhoeu** [EducationLink/vue-tel-input#66]
Hi! it would be nice to have the country code next to the flag like this ![image](https://user-images.githubusercontent.com/12591153/53777168-83094d00-3f4c-11e9-91e2-c481c764ef29.png)

**Comment by flangofas** [comment]
@SamanthaChhoeu @iamstevendao PR up

**Comment by iamstevendao** [comment]
@flangofas, thanks, done in `v2.0.18`.
