### ISSUE TITLE
Validates the phone number wrongly

### ISSUE THREAD

**Issue by rshmtud** [EducationLink/vue-tel-input#68]
I was testing for a phone number in Germany (DE) here : https://educationlink.github.io/vue-tel-input/ and it validates just the number '+49 1234' which it shouldn't. So, I checked Google's libphonenumber here https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
and it didn't validate '+49 1234'. So something is mistaken there.

**Comment by SokarSky** [comment]
The same with the numbers of South Korea. Example number +82598526969

**Comment by iamstevendao** [comment]
We start using [awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber) from [v3.1.0]() and it looks better with the validation, feel free to re-open if you guys found any issues.

**Comment by leyap** [comment]
After replace libphonenumber-js to awesome-phonenumber, Validates the phone number wrongly, like : +6281285555186

**Comment by iamstevendao** [comment]
@leyap, Can you try with [v.3.1.3](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.3)? this was a bug of multiple hyphen characters after formatting.

**Comment by leyap** [comment]
I tried, it resolved, thanks

**Comment by ckrishna007** [comment]
mode: 'internaitonal', adds +xx, else it adds 0 to the number.
I still face this issue with versions above 3.2.1
Issue is not present in 2.2.5
