### ISSUE TITLE
Placeholder option - number example based on defaultCountry

### ISSUE THREAD

**Issue by lukaVarga** [EducationLink/vue-tel-input#70]
Hi. First off, thanks for creating this plugin :)

I just wanted to ask whether there are any plans to add (and expose, code-wise?) properly formatted phone number examples for different countries, so we could choose to use an example of a properly formatted telephone number as placeholder values (based on whichever country is selected)?
That way we could have eg `+1 202 555 0146` as placeholder value in case US is chosen by user (or set as `defaultCountry`), or eg. `+386 31 100 100` in case Slovenia us chosen by the user, ...

**Comment by iamstevendao** [comment]
@lukaVarga, thanks for using it :). We have added `country-changed` event, where you can get the current active country of the input, available in [v4.2.2](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.2).

**Comment by koraykupe** [comment]
It works, but we need to add all these example formats manually for every country. :(

**Comment by iamstevendao** [comment]
@koraykupe, if you have a set of placeholders for each country then you can match it with the current country, no? what is your use case?

**Comment by koraykupe** [comment]
I mean I need to find these placeholders data from somewhere. It comes with the package itself on intlTelInput. Maybe you could add it and make it optional.

**Comment by iamstevendao** [comment]
@koraykupe ok I will check it out.

**Comment by lukaVarga** [comment]
Sorry for late response. Like @koraykupe said, it would be great if the placeholders example data was included in the `vue-tel-input` so we could opt-in to use that data :)

**Comment by iamstevendao** [comment]
Solved in #122
