### ISSUE TITLE
bootstrap 4 styling break

### ISSUE THREAD

**Issue by R00118189** [EducationLink/vue-tel-input#72]
after update to newest version 2.0.18

![image](https://user-images.githubusercontent.com/6721357/54879950-505dc080-4e37-11e9-9aad-78ac46b69d28.png)

before 

![image](https://user-images.githubusercontent.com/6721357/54879955-5ce21900-4e37-11e9-88be-63d752a01b0e.png)

code for the field did not change
```
    <vue-tel-input 
    v-model="form.data.phone" 
    name="phone" 
    ref="phone" 
    id="phone" 
    v-validate="{ phoneNumber:true }"
    class="form-control" 
    :class="{'is-invalid':errors.has('phone')}"
    autocomplete="none" 
    placeholder="Mobile">
    </vue-tel-input>
```

**Comment by iamstevendao** [comment]
Can you inspect the element and show me the style of this input?
We updated to v2.0.18 and it's fine here.

**Comment by R00118189** [comment]
there is no difference except this tiny commenting tag `<!---->`  
```html
<div class="form-group"><label for="phone" class="form-control-label">Mobile</label>
    <div data-v-7040b622="" class="vue-tel-input form-control" id="phone">
        <div data-v-7040b622="" tabindex="0" class="dropdown"><span data-v-7040b622="" class="selection">
                <div data-v-7040b622="" class="iti-flag ie"></div>
                *<!---->* <span data-v-7040b622="" class="dropdown-arrow">▼</span>
            </span>
```

the issue is probably in css itself

**Comment by iamstevendao** [comment]
@R00118189 Did you update the bootstrap? Maybe new bootstrap breaks it?

**Comment by R00118189** [comment]
No bootstrap updates, I am switching your package 2.0.17 to 2.0.18 and back, with .18 the layout is different even bootstrap version stays the same. the css did not change, inspected code did not change. I cant see how I can help to find the cause. it is possible something brake in the theme I am using but it shouldn't as all html and css is the same.

**Comment by iamstevendao** [comment]
hmm I dont know how to help with that. Is there an easy way for me to see what happen? You can put your component somewhere like repl.it?
