### ISSUE TITLE
Change country code with disabledFormatting set to false

### ISSUE THREAD

**Issue by bagbyte** [EducationLink/vue-tel-input#74]
Would be cool if, when the disabledFormatting = false, when the user changes the country, the old country code is automatically replaced with the new one.

#### Step 1
Country: France (+33)
Formatted number: +33 3 33 33 33 33
isValid: true

#### Step 2
The user changes the country
Country: Switzerland (+41)
Formatted number: +41333333333
isValid: false

#### Step 3
The user changes the country
Country: Germany (+49)
Formatted number: +49 33333 333
isValid: true

**Comment by iamstevendao** [comment]
@bagbyte, sorry for the delay. Changing country will change the dial code function will be available from [v3.1.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.0).
