### ISSUE TITLE
How to add focus?

### ISSUE THREAD

**Issue by bigperson** [EducationLink/vue-tel-input#77]
Hi. How to add focus in input after mounted component?

**Comment by Mach12** [comment]
I don't know if it's the best solution, but I had this problem and I just used [refs](https://vuejs.org/v2/api/#ref).

- Put a `ref` on the phone input component.
- In the parent component, do something like `this.$refs.phoneInput.$refs.input.focus()` (assuming that the ref on the phone component is called `phoneInput`)

I used the fact that this component stores a ref to its inner input. This isn't officially documented though, so either it needs to be documented, or one should avoid assuming that the ref to the `<input>` will remain.

**Comment by iamstevendao** [comment]
From `v2.2.0` we have `focus()` method, thus you can use `this.$refs.phoneInput.focus()` to set the focus on the input of `vue-tel-input`.
