### ISSUE TITLE
Webpack size

### ISSUE THREAD

**Issue by jagould2012** [EducationLink/vue-tel-input#78]
Any suggestions on what can be done to reduce the size of the module? Is something extra being bundled with it, or is the size of all the flag images?

As you can see, it represents a very large chunk of my project - bigger than Vuetify

<img width="1337" alt="Screen Shot 2019-04-21 at 4 46 30 PM" src="https://user-images.githubusercontent.com/7483145/56475360-1a6f2480-6455-11e9-9373-1a4e5ca6ec65.png">

**Comment by iamstevendao** [comment]
I might never notice without your issue that we are building into `umd` instead of `commonjs` module, it should be fixed by bbadda59b1628145d17169f9352c358abcf4a6c1.
The v2.1.3 is published, which brings the size down from ~400KB to 137KB
Thank you!

**Comment by maverickpravin** [comment]
![Capture1](https://user-images.githubusercontent.com/11708491/68791930-62170100-0670-11ea-985c-ac4d6211fe65.PNG)
I dont know why its showing 400kb @iamstevendao
