### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by suryadana** [EducationLink/vue-tel-input#79]
I hope the package can use on the typescript.

**Comment by iamstevendao** [comment]
@suryadana, Do you mean your project is using typescript and unable to add `vue-tel-input`?

**Comment by suryadana** [comment]
@iamstevendao i mean typescript need a declaration. I seem error like this ` Could not find a declaration file for module 'vue-tel-input'.`.

**Comment by suryadana** [comment]
I had to make PR on [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35026#discussion_r279099432) and already merged. The problem can solve with install @types/vue-tel-input with ```npm install --save-dev @types/vue-tel-input```

**Comment by iamstevendao** [comment]
@suryadana Sweet!!!. Thanks for your help, if you want to put some references in the README just create a PR and I will merge :)
