### ISSUE TITLE
:disabledFetchingCountry="false" is not working after the new release

### ISSUE THREAD

**Issue by Mobeidat** [EducationLink/vue-tel-input#80]

**Comment by iamstevendao** [comment]
@Mobeidat Are you using v2.1.3? Can you reproduce it in the [here](https://codesandbox.io/s/0yyyk45q7w?fontsize=14&module=%2Fsrc%2FApp.vue&moduleview=1)?

**Comment by iamstevendao** [comment]
Close due to inactivity.

**Comment by constagorgan** [comment]
I am on the latest current version: `v5.0.3` (as of 21.01.2021)

And setting the `disabledFetchingCountry` flag to `true` doesn't seem to have any effect:

The **component**:
```
<template>
  ...
  <vue-tel-input v-model="phoneNumber"
                 v-bind="vueTelInputProps">
  ...
</template>
<script>
  ...
  data() {
    return {
      vueTelInputProps: {
        mode: "international",
        disabledFetchingCountry: true,
        preferredCountries: ['us']
      }
    }
  }
  ...
</script>
```

In the **browser**:
![image](https://user-images.githubusercontent.com/9217700/105383397-bffe8b80-5c19-11eb-93fc-cde68c92bb5d.png)
