### ISSUE TITLE
Active country code doesn't change if disabledFetchingCountry is true

### ISSUE THREAD

**Issue by nmult13** [EducationLink/vue-tel-input#89]
Hi!
When the component is first loaded and prop disabledFetchingCountry = true, active country code in input doesn't change, because method getCountry() changes activeCountry later, then `this.phone = '+' + this.activeCountry.dialCode;`

**Comment by iamstevendao** [comment]
@nmult13 When `disabledFetchingCountry = true` we don't fetch the country by user's IP anymore. But it will fall to the first country in the preferred list (can be set via `preferredCountries`).
Did I answer your concern?

**Comment by nmult13** [comment]
Sorry, I made a mistake, when disabledFetchingCountry = false active country code in input doesn't change

**Comment by iamstevendao** [comment]
@nmult13 Are you able to reproduce somewhere? maybe in the [Playground](https://codesandbox.io/s/0yyyk45q7w?fontsize=14&module=%2Fsrc%2FApp.vue&moduleview=1) ?

**Comment by iamstevendao** [comment]
Fixed by 154696bde5ef8b261182a181019cd5878034655f, available from [v2.4.3](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.3)
