### ISSUE TITLE
Errors: Callback, timeout and preselected country not available

### ISSUE THREAD

**Issue by CristianaPereira** [EducationLink/vue-tel-input#9]
I'm doing everything as you did in the example, still it gives me errors.
i just wanted some country pre-selected 

![screen shot 2018-05-17 at 13 59 09](https://user-images.githubusercontent.com/15370124/40178876-a94569d4-59da-11e8-86ca-641ed013bcad.png)

My code:

<template lang="html">
  <div class="domainContactForm">
    <vue-tel-input v-model="phone" @onInput="onInput">
     </vue-tel-input>
  </div>

</template>

<script>
import VueTelInput from 'vue-tel-input'

export default {
  data() {
    return {
      phone:''
    }
  },
  components: {
    'vue-tel-input': VueTelInput
  },
  methods: {
    /**
     * @param {string} number
     * the phone number inputted by user, will be formatted along with country code
     * // Ex: inputted: (AU) 0432 432 432
     * // number = '+61432421546'
     *
     * @param {Boolean} isValid
     * @param {string} country
     */
     onInput({ number, isValid, country }) {
       console.log(number, isValid, country);
     },
  }
}
</script>

<style>

  .domainContactForm {
      width: 100%;
  }
  .dropdown-menu.show {
    max-height: 300px;
    overflow: scroll;
  }

</style>

**Comment by iamstevendao** [comment]
hmm, somehow it's unable to fetch your location.
can you check if your code blocks the domain?
it needs to fetch from https://ipinfo.io/json

**Comment by iamstevendao** [comment]
v1.3.9 is up. it might not fix your problem but at least will not throw some ugly errors

**Comment by CristianaPereira** [comment]
Thank you for answering so quickly

I'm getting a 429 on https://ipinfo.io/json. Not sure why...everything else is ok..

**Comment by iamstevendao** [comment]
Added option to disable auto-fetching user's country in [v2.0.0](https://www.npmjs.com/package/vue-tel-input), please check [README](https://www.npmjs.com/package/vue-tel-input)
