### ISSUE TITLE
Label “for” and Input “id”

### ISSUE THREAD

**Issue by webistomin** [EducationLink/vue-tel-input#90]
Hi! How can i add `id` to `input`? I want to use it with `<label for="id"/>` attribute.

**Comment by SteveLeeRCI** [comment]
Hi, webistomin!
Please use this one!
<label for="telInput">Mobile Number</label>
        <vue-tel-input
          id="telInput"
          v-model="phone"
          v-on:onValidate="onValidate"
          placeholder="Enter your mobile number!"
          type="number"
        ></vue-tel-input>

**Comment by webistomin** [comment]
> Hi, webistomin!
> Please use this one!
> ` <vue-tel-input id="telInput" v-model="phone" v-on:onValidate="onValidate" placeholder="Enter your mobile number!" type="number" ></vue-tel-input>`

In this case `id`  will apply to `<div>` wrapper but i need it on `<input>`

**Comment by pchapl** [comment]
You can get access to the `input` element via `$refs`:

```html
<vue-tel-input ... ref="inputWrapper" ></vue-tel-input>
```
```js
mounted: function () {
    this.$refs.inputWrapper.$refs.input.id = 'telInput';
},
```

**Comment by webistomin** [comment]
> You can get access to the `input` element via `$refs`:
> 
> ```
> <vue-tel-input ... ref="inputWrapper" ></vue-tel-input>
> ```
> 
> ```js
> mounted: function () {
>     this.$refs.inputWrapper.$refs.input.id = 'telInput';
> },
> ```

Thank you! :)

**Comment by jevgenigavrilov** [comment]
Can this be added to the pre-defined properties? I think accessibility should be taken more seriously and there should be an option to set up the `id` through prop. There is virtually no scenario where `id` and corresponding`label` shouldn't be tied toghter through `for` and `id` attributes.

**Comment by pxwee5** [comment]
I don't think this is working anymore.

**Comment by iamstevendao** [comment]
You guys should be able to add `id` for the input via `inputId` prop from [v2.4.1](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.1).
