### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by yoann-chambrun** [EducationLink/vue-tel-input#91]
When i want to display in Internet Explorer 11, i have a Syntax Error from get-json package.

**Comment by iamstevendao** [comment]
@yoann-chambrun Would you mind taking a screenshot or some text of the error?

**Comment by yoann-chambrun** [comment]
![Capture d’écran de 2019-06-07 18-54-50](https://user-images.githubusercontent.com/39832950/59120661-46d3f700-8956-11e9-8a0c-d7410f4c0586.png)

**Comment by iamstevendao** [comment]
We stop using `get-json` from [v2.3.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.3.0) and use `simple-get` instead. Do you want to check it out to see if it fixes the error?

**Comment by giliomeejg** [comment]
Just confirming that IE11 is giving the attached error.

![Screenshot 2019-07-17 at 08 44 01 (2)](https://user-images.githubusercontent.com/19786448/61353180-72a89d80-a86f-11e9-810a-428e360ebb29.png)

**Comment by rogue-bryan** [comment]
Same as @giliomeejg, we'd love to use this component, but breaking in IE:

![image](https://user-images.githubusercontent.com/6431115/61384811-f3b76300-a876-11e9-9a01-4d1d0d5e3fd4.png)

**Comment by webchiper** [comment]
Version 2.4.2
![image](https://user-images.githubusercontent.com/43057473/61602523-2771fe80-ac64-11e9-90f6-3a56397c7b96.png)
![image](https://user-images.githubusercontent.com/43057473/61602609-7c157980-ac64-11e9-95f0-275d25f259e7.png)

**Comment by Cookizza** [comment]
I am getting this also :(

**Comment by iamstevendao** [comment]
It should be fixed in [v3.0.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.0.0). The demo page is now also working in IE 11.
