### ISSUE TITLE
v2.2.0 has breaking changes, should not be a minor

### ISSUE THREAD

**Issue by msanzv** [EducationLink/vue-tel-input#94]
Yesterday our signup page stopped working because the form wasn't validating, and after an afternoon of investigation, we tracked it down to this library.

The changes in v2.2.0, specifically in commit https://github.com/EducationLink/vue-tel-input/commit/b5187c2306236b1286ce29d9dd61f0310ee2aa4c, changed the API quite a lot by both changing the names of the emitted events and also adding a parameter in one of them. I think those kind of changes belong to a major version, or at least to a version that accepts both APIs and marks the old one as deprecated in the docs.

I already tracked it down and made those changes, but this will probably happen to everyone using those events, so writing this here in case case it helps others.

**Comment by iamstevendao** [comment]
@msanzv. Sorry and thanks for your help! I would definitely take a look into it this weekend. Along with the backwards-compatible changes, I might add the [releases of Github](https://help.github.com/en/articles/creating-releases) but I'm not sure it would be a good practise. Any recommendation?

**Comment by iamstevendao** [comment]
Fixed in [v2.2.5](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.2.5) (83f2737bf65e4737be6c3a45dc40f4c37b75c496)

**Comment by msanzv** [comment]
Thank you!
