### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by kevcodez** [EducationLink/vue-tel-input#95]
I am trying to use vue-tel-input within nuxtjs and keep getting the exception above, when having a predefined value.

```html
          <vue-tel-input
            v-model="phone"
            name="Telefonnummer"
            type="text"
            :disabled-fetching-country="true"
            placeholder="Telefonnummer eintragen"
            :only-countries="['DE']"
          />
```

When defining an empty value in the components state, it works fine:

```ts
export default class CustomerAddressesForm extends Vue {
    phone: string = ''
}
```

However, when predefining the value, I get the exception **Cannot read property 'toLowerCase' of undefined**

```ts
export default class CustomerAddressesForm extends Vue {
    phone: string = '1234'
}
```

When disabling flags `:enabled-flags="false"`, it does work.

**Comment by iamstevendao** [comment]
What version are you using? Are you able to reproduce in the [Codesanbox](https://codesandbox.io/s/0yyyk45q7w?fontsize=14&module=%2Fsrc%2FApp.vue&moduleview=1) (using our latest version)?
I have been trying in dev but no luck to get the error.

**Comment by kevcodez** [comment]
@iamstevendao I am using the latest version of vue-tel-input within the latest version of Nuxt.js. I will try to provide a sample asap

**Comment by kevcodez** [comment]
I am unable to reproduce this myself, so I am going to close this for now.
