### ISSUE TITLE
Format the number on create when is not formatted correctly

### ISSUE THREAD

**Issue by Hydrog3n** [EducationLink/vue-tel-input#98]
When I set a v-model and the phone number is not formatted correctly. It still not format until i change a number

**Comment by iamstevendao** [comment]
@Hydrog3n, would you mind reproducing it in the [Playground](https://codesandbox.io/s/0yyyk45q7w?fontsize=14&module=%2Fsrc%2FApp.vue&moduleview=1)?

**Comment by Hydrog3n** [comment]
@iamstevendao Yes this exemple doen't format the number until you change a number 
https://codesandbox.io/s/vue-template-rrx1o

**Comment by iamstevendao** [comment]
@Hydrog3n, It should be fixed in [v3.1.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.1.0). Now you also have the option to convert it to `national` or `international` mode. Here is the sample in 'international' mode: https://jsfiddle.net/iamstevendao/6dyop3h7/

**Comment by Hydrog3n** [comment]
Hello @iamstevendao Thank you for the fix and the feature :)
